### ISSUE TITLE
TextField  : FATAL EXCEPTION  After Upgrading From "0.20.1" -> "0.23.1" 

### ISSUE THREAD

**Issue by YOUSSEFELJAYAD** [kiwicom/orbit-compose#321]
Implimentation :

```
OrbitV : 0.23.1
+ import kiwi.orbit.compose.ui.controls.TextField
+ var KeySearch by remember { mutableStateOf("") }

           TextField(
                            value = KeySearch,
                            onValueChange = {
                                KeySearch = it
                            },
                            leadingIcon = { Icon(Icons.Search, contentDescription = null) },
                            keyboardOptions = KeyboardOptions(
                                keyboardType = KeyboardType.Text,
                                imeAction = ImeAction.Search,
                            ),
                            keyboardActions = KeyboardActions(
                                onNext = {

                                },
                            ),
                            modifier = Modifier
                                .fillMaxWidth()
                                
                        )
```
🔴  **_To reproduce the issue you have to use a TextField together with a KeyboardActions_** 🧧 

Expt : 

**No static field $stable of type I in class Landroidx/compose/foundation/text/KeyboardActions; or its superclasses (declaration of 'androidx.compose.foundation.text.KeyboardActions' appears in /data/app/~~CDFp8fOao4_qu-UdRs1dGQ==/com.flex.packageName.debug-zeXBGRC8ROTie88GT3KfPQ==/base.apk)**

Logs : 
```
java.lang.NoSuchFieldError: No static field $stable of type I in class Landroidx/compose/foundation/text/KeyboardActions; or its superclasses (declaration of 'androidx.compose.foundation.text.KeyboardActions' appears in /data/app/~~CDFp8fOao4_qu-UdRs1dGQ==/com.flex.packageName.debug-zeXBGRC8ROTie88GT3KfPQ==/base.apk)
        at kiwi.orbit.compose.ui.controls.TextFieldKt.TextField(TextField.kt:99)
        **at com.flex.vpay.ui.View.SearchViewKt$SearchView$1$1.invoke(SearchView.kt:59)
        at com.flex.vpay.ui.View.SearchViewKt$SearchView$1$1.invoke(SearchView.kt:47)**
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at kiwi.orbit.compose.ui.controls.TopAppBarLargeKt$TopAppBarLarge$3.invoke(TopAppBarLarge.kt:90)
        at kiwi.orbit.compose.ui.controls.TopAppBarLargeKt$TopAppBarLarge$3.invoke(TopAppBarLarge.kt:84)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at kiwi.orbit.compose.ui.controls.TopAppBarKt$TopAppBarLayout$2$1$3$1.invoke(TopAppBar.kt:218)
        at kiwi.orbit.compose.ui.controls.TopAppBarKt$TopAppBarLayout$2$1$3$1.invoke(TopAppBar.kt:217)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.compose.material.TextKt.ProvideTextStyle(Text.kt:265)
        at kiwi.orbit.compose.ui.foundation.TextStyleKt.ProvideMergedTextStyle(TextStyle.kt:16)
        at kiwi.orbit.compose.ui.controls.TopAppBarKt$TopAppBarLayout$2$1.invoke(TopAppBar.kt:217)
        at kiwi.orbit.compose.ui.controls.TopAppBarKt$TopAppBarLayout$2$1.invoke(TopAppBar.kt:202)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at kiwi.orbit.compose.ui.controls.TopAppBarKt.TopAppBarLayout(TopAppBar.kt:199)
        at kiwi.orbit.compose.ui.controls.TopAppBarLargeKt$TwoRowsTopAppBar$2.invoke(TopAppBarLarge.kt:166)
        at kiwi.orbit.compose.ui.controls.TopAppBarLargeKt$TwoRowsTopAppBar$2.invoke(TopAppBarLarge.kt:160)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at kiwi.orbit.compose.ui.controls.SurfaceKt$Surface$1.invoke(Surface.kt:66)
        at kiwi.orbit.compose.ui.controls.SurfaceKt$Surface$1.invoke(Surface.kt:49)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at kiwi.orbit.compose.ui.controls.SurfaceKt.Surface-F-jzlyU(Surface.kt:45)
        at kiwi.orbit.compose.ui.controls.TopAppBarLargeKt.TwoRowsTopAppBar-0vH8DBg(TopAppBarLarge.kt:156)
        at kiwi.orbit.compose.ui.controls.TopAppBarLargeKt.TopAppBarLarge-0vH8DBg(TopAppBarLarge.kt:82)
        at com.flex.vpay.ui.View.SearchViewKt$SearchView$1.invoke(SearchView.kt:46)
        at com.flex.vpay.ui.View.SearchViewKt$SearchView$1.invoke(SearchView.kt:45)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at kiwi.orbit.compose.ui.controls.ScaffoldKt.ScaffoldLayout(Scaffold.kt:75)
        at kiwi.orbit.compose.ui.controls.ScaffoldKt.access$ScaffoldLayout(Scaffold.kt:1)
E/AndroidRuntime:     at kiwi.orbit.compose.ui.controls.ScaffoldKt$Scaffold$3.invoke(Scaffold.kt:53)
        at kiwi.orbit.compose.ui.controls.ScaffoldKt$Scaffold$3.invoke(Scaffold.kt:52)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at kiwi.orbit.compose.ui.controls.SurfaceKt$Surface$1.invoke(Surface.kt:66)
        at kiwi.orbit.compose.ui.controls.SurfaceKt$Surface$1.invoke(Surface.kt:49)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at kiwi.orbit.compose.ui.controls.SurfaceKt.Surface-F-jzlyU(Surface.kt:45)
        at kiwi.orbit.compose.ui.controls.ScaffoldKt.Scaffold-LHOAhiI(Scaffold.kt:48)
        at com.flex.vpay.ui.View.SearchViewKt.SearchView(SearchView.kt:44)
        at com.flex.vpay.ui.View.destinations.SearchViewDestination.Content(SearchViewDestination.kt:39)
        at com.ramcosta.composedestinations.animations.AnimatedNavHostEngine.CallComposable(AnimatedNavHostEngine.kt:286)
        at com.ramcosta.composedestinations.animations.AnimatedNavHostEngine.access$CallComposable(AnimatedNavHostEngine.kt:58)
        at com.ramcosta.composedestinations.animations.AnimatedNavHostEngine$addAnimatedComposable$1$5.invoke(AnimatedNavHostEngine.kt:206)
        at com.ramcosta.composedestinations.animations.AnimatedNavHostEngine$addAnimatedComposable$1$5.invoke(AnimatedNavHostEngine.kt:202)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:135)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$9$1.invoke(AnimatedNavHost.kt:223)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$9$1.invoke(AnimatedNavHost.kt:221)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
        at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:60)
        at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
        at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:52)
        at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:51)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider(NavBackStackEntryProvider.kt:47)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$9.invoke(AnimatedNavHost.kt:221)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$9.invoke(AnimatedNavHost.kt:209)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:135)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1$4.invoke(AnimatedContent.kt:658)
        at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1$4.invoke(AnimatedContent.kt:648)
E/AndroidRuntime:     at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:939)
        at androidx.compose.animation.AnimatedVisibilityKt.AnimatedVisibility(AnimatedVisibility.kt:607)
        at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1.invoke(AnimatedContent.kt:638)
        at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1.invoke(AnimatedContent.kt:625)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:671)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:195)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$11.invoke(Unknown Source:23)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$11.invoke(Unknown Source:10)
        at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:162)
        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2435)
        at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2703)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3326)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3304)
        at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
        at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3304)
        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3269)
        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:771)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1048)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:125)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:542)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:511)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1386)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1396)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1033)
        at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:397)
        at android.view.Choreographer.doFrame(Choreographer.java:900)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1371)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:240)
        at android.os.Looper.loop(Looper.java:351)
        at android.app.ActivityThread.main(ActivityThread.java:8321)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1012)
E/AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@7bd322d, androidx.compose.ui.platform.MotionDurationScaleImpl@ca64362, StandaloneCoroutine{Cancelling}@b1ebcf3, AndroidUiDispatcher@9aadb0]
```

**Comment by YOUSSEFELJAYAD** [comment]
this issue is being tracked in https://issuetracker.google.com/issues/265172081 .
